# Generated by Django 3.1.7 on 2021-03-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_num',
            field=models.IntegerField(null=True),
        ),
    ]
